CREATE TABLE Pokedex (
    NUM_POKEDEX INT PRIMARY KEY,
    NOM_POKEMON VARCHAR(20) NOT NULL,
    IMG_FRONTAL VARCHAR(100) NOT NULL,
    IMG_TRASERA VARCHAR(100) NOT NULL,
    SONIDO VARCHAR(100) NOT NULL,
    NIVEL_EVOLUCION INT,
    TIPO1 VARCHAR(20) NOT NULL, 
    TIPO2 VARCHAR(20)
);

INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, TIPO1, TIPO2, IMG_FRONTAL, IMG_TRASERA, SONIDO, NIVEL_EVOLUCION) VALUES (1, 'Bulbasaur', 'Planta', 'Veneno', '001.png', '001_back.png', '001.wav', 16);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, TIPO1, TIPO2, IMG_FRONTAL, IMG_TRASERA, SONIDO, NIVEL_EVOLUCION) VALUES (2, 'Ivysaur', 'Planta', 'Veneno', '002.png', '002_back.png', '002.wav', 32);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, TIPO1, TIPO2, IMG_FRONTAL, IMG_TRASERA, SONIDO, NIVEL_EVOLUCION) VALUES (3, 'Venusaur', 'Planta', 'Veneno', '003.png', '003_back.png', '003.wav', NULL);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, TIPO1, TIPO2, IMG_FRONTAL, IMG_TRASERA, SONIDO, NIVEL_EVOLUCION) VALUES (4, 'Charmander', 'Fuego', NULL, '004.png', '004_back.png', '004.wav', 16);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, TIPO1, TIPO2, IMG_FRONTAL, IMG_TRASERA, SONIDO, NIVEL_EVOLUCION) VALUES (5, 'Charmeleon', 'Fuego', NULL, '005.png', '005_back.png', '005.wav', 36);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, TIPO1, TIPO2, IMG_FRONTAL, IMG_TRASERA, SONIDO, NIVEL_EVOLUCION) VALUES (6, 'Charizard', 'Fuego', 'Volador', '006.png', '006_back.png', '006.wav', NULL);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, TIPO1, TIPO2, IMG_FRONTAL, IMG_TRASERA, SONIDO, NIVEL_EVOLUCION) VALUES (7, 'Squirtle', 'Agua', NULL, '007.png', '007_back.png', '007.wav', 16);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, TIPO1, TIPO2, IMG_FRONTAL, IMG_TRASERA, SONIDO, NIVEL_EVOLUCION) VALUES (8, 'Wartortle', 'Agua', NULL, '008.png', '008_back.png', '008.wav', 36);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, TIPO1, TIPO2, IMG_FRONTAL, IMG_TRASERA, SONIDO, NIVEL_EVOLUCION) VALUES (9, 'Blastoise', 'Agua', NULL, '009.png', '009_back.png', '009.wav', NULL);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, TIPO1, TIPO2, IMG_FRONTAL, IMG_TRASERA, SONIDO, NIVEL_EVOLUCION) VALUES (10, 'Caterpie', 'Bicho', NULL, '010.png', '010_back.png', '010.wav', 7);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, TIPO1, TIPO2, IMG_FRONTAL, IMG_TRASERA, SONIDO, NIVEL_EVOLUCION) VALUES (11, 'Metapod', 'Bicho', NULL, '011.png', '011_back.png', '011.wav', 10);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, TIPO1, TIPO2, IMG_FRONTAL, IMG_TRASERA, SONIDO, NIVEL_EVOLUCION) VALUES (12, 'Butterfree', 'Bicho', 'Volador', '012.png', '012_back.png', '012.wav', NULL);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, TIPO1, TIPO2, IMG_FRONTAL, IMG_TRASERA, SONIDO, NIVEL_EVOLUCION) VALUES (13, 'Weedle', 'Bicho', 'Veneno', '013.png', '013_back.png', '013.wav', 7);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, TIPO1, TIPO2, IMG_FRONTAL, IMG_TRASERA, SONIDO, NIVEL_EVOLUCION) VALUES (14, 'Kakuna', 'Bicho', 'Veneno', '014.png', '014_back.png', '014.wav', 10);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, TIPO1, TIPO2, IMG_FRONTAL, IMG_TRASERA, SONIDO, NIVEL_EVOLUCION) VALUES (15, 'Beedrill', 'Bicho', 'Veneno', '015.png', '015_back.png', '015.wav', NULL);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, TIPO1, TIPO2, IMG_FRONTAL, IMG_TRASERA, SONIDO, NIVEL_EVOLUCION) VALUES (16, 'Pidgey', 'Normal', 'Volador', '016.png', '016_back.png', '016.wav', 18);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, TIPO1, TIPO2, IMG_FRONTAL, IMG_TRASERA, SONIDO, NIVEL_EVOLUCION) VALUES (17, 'Pidgeotto', 'Normal', 'Volador', '017.png', '017_back.png', '017.wav', 36);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, TIPO1, TIPO2, IMG_FRONTAL, IMG_TRASERA, SONIDO, NIVEL_EVOLUCION) VALUES (18, 'Pidgeot', 'Normal', 'Volador', '018.png', '018.png', '018.wav', NULL);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, TIPO1, TIPO2, IMG_FRONTAL, IMG_TRASERA, SONIDO, NIVEL_EVOLUCION) VALUES (19, 'Rattata', 'Normal', NULL, '019.png', '019.png', '019.wav', 20);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, TIPO1, TIPO2, IMG_FRONTAL, IMG_TRASERA, SONIDO, NIVEL_EVOLUCION) VALUES (20, 'Raticate', 'Normal', NULL, '020.png', '020_back.png', '020.wav', NULL);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, TIPO1, TIPO2, IMG_FRONTAL, IMG_TRASERA, SONIDO, NIVEL_EVOLUCION) VALUES (21, 'Spearow', 'Normal', 'Volador', '021.png', '021_back.png', '021.wav', 20);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, TIPO1, TIPO2, IMG_FRONTAL, IMG_TRASERA, SONIDO, NIVEL_EVOLUCION) VALUES (22, 'Fearow', 'Normal', 'Volador', '022.png', '022_back.png', '022.wav', NULL);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, TIPO1, TIPO2, IMG_FRONTAL, IMG_TRASERA, SONIDO, NIVEL_EVOLUCION) VALUES (23, 'Ekans', 'Veneno', NULL, '023.png', '023_back.png', '023.wav', 22);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, TIPO1, TIPO2, IMG_FRONTAL, IMG_TRASERA, SONIDO, NIVEL_EVOLUCION) VALUES (24, 'Arbok', 'Veneno', NULL, '024.png', '024_back.png', '024.wav', NULL);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, TIPO1, TIPO2, IMG_FRONTAL, IMG_TRASERA, SONIDO, NIVEL_EVOLUCION) VALUES (25, 'Pikachu', 'Eléctrico', NULL, '025.png', '025_back.png', '025.wav', 25);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, TIPO1, TIPO2, IMG_FRONTAL, IMG_TRASERA, SONIDO, NIVEL_EVOLUCION) VALUES (26, 'Raichu', 'Eléctrico', NULL, '026.png', '026_back.png', '026.wav', NULL);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, TIPO1, TIPO2, IMG_FRONTAL, IMG_TRASERA, SONIDO, NIVEL_EVOLUCION) VALUES (27, 'Sandshrew', 'Tierra', NULL, '027.png', '027_back.png', '027.wav', 22);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, TIPO1, TIPO2, IMG_FRONTAL, IMG_TRASERA, SONIDO, NIVEL_EVOLUCION) VALUES (28, 'Sandslash', 'Tierra', NULL, '028.png', '028_back.png', '028.wav', NULL);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, TIPO1, TIPO2, IMG_FRONTAL, IMG_TRASERA, SONIDO, NIVEL_EVOLUCION) VALUES (29, 'Nidoran♀', 'Veneno', NULL, '029.png', '029.png', '029.wav', 16);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, TIPO1, TIPO2, IMG_FRONTAL, IMG_TRASERA, SONIDO, NIVEL_EVOLUCION) VALUES (30, 'Nidorina', 'Veneno', NULL, '030.png', '030_back.png', '030.wav', 36);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, TIPO1, TIPO2, IMG_FRONTAL, IMG_TRASERA, SONIDO, NIVEL_EVOLUCION) VALUES (31, 'Nidoqueen', 'Veneno', 'Tierra', '031.png', '031_back.png', '031.wav', NULL);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, TIPO1, TIPO2, IMG_FRONTAL, IMG_TRASERA, SONIDO, NIVEL_EVOLUCION) VALUES (32, 'Nidoran♂', 'Veneno', NULL, '032.png', '032_back.png', '032.wav', 16);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, TIPO1, TIPO2, IMG_FRONTAL, IMG_TRASERA, SONIDO, NIVEL_EVOLUCION) VALUES (33, 'Nidorino', 'Veneno', NULL, '033.png', '033_back.png', '033.wav', 36);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, TIPO1, TIPO2, IMG_FRONTAL, IMG_TRASERA, SONIDO, NIVEL_EVOLUCION) VALUES (34, 'Nidoking', 'Veneno', 'Tierra', '034.png', '034_back.png', '034.wav', NULL);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, TIPO1, TIPO2, IMG_FRONTAL, IMG_TRASERA, SONIDO, NIVEL_EVOLUCION) VALUES (35, 'Clefairy', 'Hada', NULL, '035.png', '035_back.png', '035.wav', 16);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, TIPO1, TIPO2, IMG_FRONTAL, IMG_TRASERA, SONIDO, NIVEL_EVOLUCION) VALUES (36, 'Clefable', 'Hada', NULL, '036.png', '036_back.png', '036.wav', NULL);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, TIPO1, TIPO2, IMG_FRONTAL, IMG_TRASERA, SONIDO, NIVEL_EVOLUCION) VALUES (37, 'Vulpix', 'Fuego', NULL, '037.png', '037_back.png', '037.wav', 16);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, TIPO1, TIPO2, IMG_FRONTAL, IMG_TRASERA, SONIDO, NIVEL_EVOLUCION) VALUES (38, 'Ninetales', 'Fuego', NULL, '038.png', '038_back.png', '038.wav', NULL);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, TIPO1, TIPO2, IMG_FRONTAL, IMG_TRASERA, SONIDO, NIVEL_EVOLUCION) VALUES (39, 'Jigglypuff', 'Normal', 'Hada', '039.png', '039_back.png', '039.wav', 16);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, TIPO1, TIPO2, IMG_FRONTAL, IMG_TRASERA, SONIDO, NIVEL_EVOLUCION) VALUES (40, 'Wigglytuff', 'Normal', 'Hada', '040.png', '040_back.png', '040.wav', NULL);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, TIPO1, TIPO2, IMG_FRONTAL, IMG_TRASERA, SONIDO, NIVEL_EVOLUCION) VALUES (41, 'Zubat', 'Veneno', 'Volador', '041.png', '041_back.png', '041.wav', 22);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, TIPO1, TIPO2, IMG_FRONTAL, IMG_TRASERA, SONIDO, NIVEL_EVOLUCION) VALUES (42, 'Golbat', 'Veneno', 'Volador', '042.png', '042_back.png', '042.wav', NULL);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, TIPO1, TIPO2, IMG_FRONTAL, IMG_TRASERA, SONIDO, NIVEL_EVOLUCION) VALUES (43, 'Oddish', 'Planta', 'Veneno', '043.png', '043_back.png', '043.wav', 21);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, TIPO1, TIPO2, IMG_FRONTAL, IMG_TRASERA, SONIDO, NIVEL_EVOLUCION) VALUES (44, 'Gloom', 'Planta', 'Veneno', '044.png', '044_back.png', '044.wav', 21);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, TIPO1, TIPO2, IMG_FRONTAL, IMG_TRASERA, SONIDO, NIVEL_EVOLUCION) VALUES (45, 'Vileplume', 'Planta', 'Veneno', '045.png', '045_back.png', '045.wav', 25);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, TIPO1, TIPO2, IMG_FRONTAL, IMG_TRASERA, SONIDO, NIVEL_EVOLUCION) VALUES (46, 'Paras', 'Bicho', 'Planta', '046.png', '046_back.png', '046.wav', 24);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, TIPO1, TIPO2, IMG_FRONTAL, IMG_TRASERA, SONIDO, NIVEL_EVOLUCION) VALUES (47, 'Parasect', 'Bicho', 'Planta', '047.png', '047_back.png', '047.wav', NULL);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, TIPO1, TIPO2, IMG_FRONTAL, IMG_TRASERA, SONIDO, NIVEL_EVOLUCION) VALUES (48, 'Venonat', 'Bicho', 'Veneno', '048.png', '048_back.png', '048.wav', 31);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, TIPO1, TIPO2, IMG_FRONTAL, IMG_TRASERA, SONIDO, NIVEL_EVOLUCION) VALUES (49, 'Venomoth', 'Bicho', 'Veneno', '049.png', '049_back.png', '049.wav', NULL);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, TIPO1, TIPO2, IMG_FRONTAL, IMG_TRASERA, SONIDO, NIVEL_EVOLUCION) VALUES (50, 'Diglett', 'Tierra', NULL, '050.png', '050_back.png', '050.wav', 26);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, TIPO1, TIPO2, IMG_FRONTAL, IMG_TRASERA, SONIDO, NIVEL_EVOLUCION) VALUES (51, 'Dugtrio', 'Tierra', NULL, '051.png', '051_back.png', '051.wav', NULL);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, TIPO1, TIPO2, IMG_FRONTAL, IMG_TRASERA, SONIDO, NIVEL_EVOLUCION) VALUES (52, 'Dratini', 'Dragón', NULL, '052.png', '052_back.png', '052.wav', 30);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, TIPO1, TIPO2, IMG_FRONTAL, IMG_TRASERA, SONIDO, NIVEL_EVOLUCION) VALUES (53, 'Dragonair', 'Dragón', NULL, '053.png', '053_back.png', '053.wav', 55);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, TIPO1, TIPO2, IMG_FRONTAL, IMG_TRASERA, SONIDO, NIVEL_EVOLUCION) VALUES (54, 'Dragonite', 'Dragón', 'Volador', '054.png', '054_back.png', '054.wav', NULL);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, TIPO1, TIPO2, IMG_FRONTAL, IMG_TRASERA, SONIDO, NIVEL_EVOLUCION) VALUES (55, 'Ditto', 'Normal', NULL, '055.png', '055_back.png', '055.wav', NULL);

CREATE TABLE Entrenador (
    ID_ENTRENADOR INT PRIMARY KEY,
    USUARIO VARCHAR(20) NOT NULL UNIQUE,
    PASS VARCHAR(20) NOT NULL,
    POKEDOLARES INT DEFAULT 1000
);

INSERT INTO ENTRENADOR (ID_ENTRENADOR, USUARIO, PASS, POKEDOLARES)  
VALUES (1, 'AshKetchum', '1234', 1500),  
       (2, 'Misty', '1234', 2000),  
       (3, 'Brock', '1234', DEFAULT);  


CREATE TABLE Pokemon (
    ID_POKEMON INT PRIMARY KEY,
    FKID_ENTRENADOR INT,
    FK_NUM_POKEDEX INT,
    NOMBRE VARCHAR(20),
    VITALIDAD INT NOT NULL,
    ATAQUE INT NOT NULL,
    DEFENSA INT NOT NULL,
    AT_ESPECIAL INT NOT NULL,
    DEF_ESPECIAL INT NOT NULL,
    VELOCIDAD INT NOT NULL,
    NIVEL INT,
    FERTILIDAD INT DEFAULT 5,
    SEXO CHAR(1) CHECK (SEXO IN ('H', 'M', 'X')),
    ESTADO VARCHAR(20), 
    EQUIPO INT CHECK (EQUIPO IN (1, 2, 3)), 

    FOREIGN KEY (FKID_ENTRENADOR) REFERENCES Entrenador(ID_ENTRENADOR),
    FOREIGN KEY (FK_NUM_POKEDEX) REFERENCES Pokedex(NUM_POKEDEX)
);

INSERT INTO POKEMON (ID_POKEMON, FKID_ENTRENADOR, FK_NUM_POKEDEX, NOMBRE, EQUIPO, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD, NIVEL, FERTILIDAD, SEXO, ESTADO, VITALIDAD) VALUES (6, 1, 25, 'Thunder', 1, 65, 60, 45, 55, 95, 30, 5, 'M', 'Saludable', 100);

CREATE TABLE MOVIMIENTOS (
    ID_MOVIMIENTO INT PRIMARY KEY,
    NOM_MOVIMIENTO VARCHAR(20) NOT NULL,
    NIVEL_APRENDIZAJE INT NOT NULL,
    PP_MAX INT,
    TIPO VARCHAR(20) CHECK (TIPO IN ('ATAQUE', 'ESTADO', 'MEJORA')),
    POTENCIA INT,
    TIPO_MOV VARCHAR(20),
    ESTADO VARCHAR(20),
    TURNOS INT,
    MEJORA VARCHAR(20),
    NUM INT
);

--Fuego, Hada, Veneno, Normal, Planta, Dragón

-- Movimientos de tipo Fuego (para Vulpix, Ninetales)
INSERT INTO MOVIMIENTOS VALUES (1, 'Lanzallamas', 30, 15, 'ATAQUE', 90, 'FUEGO', NULL, NULL, NULL, NULL);
INSERT INTO MOVIMIENTOS VALUES (2, 'Giro Fuego', 35, 15, 'ATAQUE', 35, 'FUEGO', NULL, NULL, NULL, NULL);
INSERT INTO MOVIMIENTOS VALUES (3, 'Ascuas', 15, 25, 'ATAQUE', 40, 'FUEGO', NULL, NULL, NULL, NULL);
INSERT INTO MOVIMIENTOS VALUES (4, 'Infierno', 50, 5, 'ATAQUE', 100, 'FUEGO', 'QUEMADO', NULL, NULL, NULL);
INSERT INTO MOVIMIENTOS VALUES (5, 'Onda Ígnea', 42, 10, 'ATAQUE', 75, 'FUEGO', NULL, NULL, NULL, NULL);
INSERT INTO MOVIMIENTOS VALUES (6, 'Rueda Fuego', 25, 25, 'ATAQUE', 60, 'FUEGO', NULL, NULL, NULL, NULL);
INSERT INTO MOVIMIENTOS VALUES (7, 'Pirotecnia', 40, 15, 'ATAQUE', 70, 'FUEGO', NULL, NULL, NULL, NULL);
INSERT INTO MOVIMIENTOS VALUES (8, 'Llama Azul', 45, 5, 'ATAQUE', 130, 'FUEGO', NULL, NULL, NULL, NULL);
INSERT INTO MOVIMIENTOS VALUES (9, 'Calcinación', 48, 5, 'ATAQUE', 80, 'FUEGO', NULL, NULL, NULL, NULL);
INSERT INTO MOVIMIENTOS VALUES (10, 'Fuego Sagrado', 50, 5, 'ATAQUE', 100, 'FUEGO', NULL, NULL, NULL, NULL);

-- Movimientos de tipo Hada (para Clefairy, Clefable, Jigglypuff, Wigglytuff)
INSERT INTO MOVIMIENTOS VALUES (11, 'Brillo Mágico', 28, 10, 'ATAQUE', 80, 'HADA', NULL, NULL, NULL, NULL);
INSERT INTO MOVIMIENTOS VALUES (12, 'Danza Hada', 40, 10, 'MEJORA', NULL, 'HADA', NULL, NULL, 'ATAQUE ESPECIAL', 2);
INSERT INTO MOVIMIENTOS VALUES (13, 'Voz Cautivadora', 20, 15, 'ATAQUE', 40, 'HADA', NULL, NULL, NULL, NULL);
INSERT INTO MOVIMIENTOS VALUES (14, 'Flecha Drenante', 48, 10, 'ATAQUE', 80, 'HADA', NULL, NULL, NULL, NULL);
INSERT INTO MOVIMIENTOS VALUES (15, 'Carantoña', 18, 20, 'ATAQUE', 90, 'HADA', NULL, NULL, NULL, NULL);
INSERT INTO MOVIMIENTOS VALUES (16, 'Luz Lunar', 45, 5, 'MEJORA', NULL, 'HADA', NULL, NULL, 'ATAQUE ESPECIAL', 2);
INSERT INTO MOVIMIENTOS VALUES (17, 'Estruendo', 30, 10, 'ATAQUE', 80, 'HADA', NULL, NULL, NULL, NULL);
INSERT INTO MOVIMIENTOS VALUES (18, 'Beso Drenaje', 25, 10, 'ATAQUE', 50, 'HADA', NULL, NULL, NULL, NULL);
INSERT INTO MOVIMIENTOS VALUES (19, 'Campana Cura', 40, 5, 'ESTADO', NULL, 'HADA', NULL, NULL, NULL, NULL);
INSERT INTO MOVIMIENTOS VALUES (20, 'Viento Feérico', 50, 5, 'ATAQUE', 100, 'HADA', NULL, NULL, NULL, NULL);

-- Movimientos de tipo Veneno (para Nidoran, Nidorina, Nidoqueen, Nidorino, Nidoking, Zubat, Golbat, Oddish, Gloom, Vileplume, Venonat, Venomoth)
INSERT INTO MOVIMIENTOS VALUES (21, 'Tóxico', 30, 10, 'ESTADO', NULL, 'VENENO', 'ENVENENADO', NULL, NULL, NULL);
INSERT INTO MOVIMIENTOS VALUES (22, 'Bomba Lodo', 35, 10, 'ATAQUE', 90, 'VENENO', NULL, NULL, NULL, NULL);
INSERT INTO MOVIMIENTOS VALUES (23, 'Onda Tóxica', 25, 10, 'ATAQUE', 65, 'VENENO', 'ENVENENADO', NULL, NULL, NULL);
INSERT INTO MOVIMIENTOS VALUES (24, 'Residuos', 40, 20, 'ESTADO', NULL, 'VENENO', 'ENVENENADO', NULL, NULL, NULL);
INSERT INTO MOVIMIENTOS VALUES (25, 'Puya Nociva', 22, 15, 'ATAQUE', 80, 'VENENO', NULL, NULL, NULL, NULL);
INSERT INTO MOVIMIENTOS VALUES (26, 'Picotazo Veneno', 20, 35, 'ATAQUE', 15, 'VENENO', 'ENVENENADO', NULL, NULL, NULL);
INSERT INTO MOVIMIENTOS VALUES (27, 'Gas Venenoso', 15, 40, 'ESTADO', NULL, 'VENENO', 'ENVENENADO', NULL, NULL, NULL);
INSERT INTO MOVIMIENTOS VALUES (28, 'Ácido', 20, 30, 'ATAQUE', 40, 'VENENO', NULL, NULL, NULL, NULL);
INSERT INTO MOVIMIENTOS VALUES (29, 'Bomba Ácida', 30, 20, 'ATAQUE', 40, 'VENENO', NULL, NULL, NULL, NULL);
INSERT INTO MOVIMIENTOS VALUES (30, 'Golpe Tóxico', 40, 10, 'ATAQUE', 65, 'VENENO', 'ENVENENADO', NULL, NULL, NULL);

-- Movimientos de tipo Normal (para Jigglypuff, Wigglytuff, Ditto)
INSERT INTO MOVIMIENTOS VALUES (31, 'Placaje', 1, 35, 'ATAQUE', 40, 'NORMAL', NULL, NULL, NULL, NULL);
INSERT INTO MOVIMIENTOS VALUES (32, 'Arañazo', 1, 35, 'ATAQUE', 40, 'NORMAL', NULL, NULL, NULL, NULL);
INSERT INTO MOVIMIENTOS VALUES (33, 'Hiperrayo', 50, 5, 'ATAQUE', 150, 'NORMAL', NULL, NULL, NULL, NULL);
INSERT INTO MOVIMIENTOS VALUES (34, 'Día de Pago', 30, 20, 'ATAQUE', 40, 'NORMAL', NULL, NULL, NULL, NULL);
INSERT INTO MOVIMIENTOS VALUES (35, 'Golpe Cuerpo', 25, 15, 'ATAQUE', 85, 'NORMAL', NULL, NULL, NULL, NULL);
INSERT INTO MOVIMIENTOS VALUES (36, 'Canto', 15, 15, 'ESTADO', NULL, 'NORMAL', 'DORMIDO', NULL, NULL, NULL);
INSERT INTO MOVIMIENTOS VALUES (37, 'Eco Voz', 30, 15, 'ATAQUE', 40, 'NORMAL', NULL, NULL, NULL, NULL);
INSERT INTO MOVIMIENTOS VALUES (38, 'Transformación', 1, 10, 'ESTADO', NULL, 'NORMAL', NULL, NULL, NULL, NULL);
INSERT INTO MOVIMIENTOS VALUES (39, 'Mimético', 30, 10, 'ESTADO', NULL, 'NORMAL', NULL, NULL, NULL, NULL);
INSERT INTO MOVIMIENTOS VALUES (40, 'Doble Filo', 45, 15, 'ATAQUE', 120, 'NORMAL', NULL, NULL, NULL, NULL);

-- Movimientos de tipo Planta (para Oddish, Gloom, Vileplume, Paras, Parasect)
INSERT INTO MOVIMIENTOS VALUES (41, 'Latigazo', 12, 10, 'ATAQUE', 45, 'PLANTA', NULL, NULL, NULL, NULL);
INSERT INTO MOVIMIENTOS VALUES (42, 'Rayo Solar', 45, 10, 'ATAQUE', 120, 'PLANTA', NULL, NULL, NULL, NULL);
INSERT INTO MOVIMIENTOS VALUES (43, 'Hoja Afilada', 30, 15, 'ATAQUE', 55, 'PLANTA', NULL, NULL, NULL, NULL);
INSERT INTO MOVIMIENTOS VALUES (44, 'Drenadoras', 25, 10, 'ATAQUE', 75, 'PLANTA', NULL, NULL, NULL, NULL);
INSERT INTO MOVIMIENTOS VALUES (45, 'Bomba Germen', 40, 15, 'ATAQUE', 80, 'PLANTA', NULL, NULL, NULL, NULL);
INSERT INTO MOVIMIENTOS VALUES (46, 'Síntesis', 30, 5, 'ESTADO', NULL, 'PLANTA', NULL, NULL, NULL, NULL);
INSERT INTO MOVIMIENTOS VALUES (47, 'Somnífero', 20, 15, 'ESTADO', NULL, 'PLANTA', 'DORMIDO', NULL, NULL, NULL);
INSERT INTO MOVIMIENTOS VALUES (48, 'Polvo Veneno', 20, 35, 'ESTADO', NULL, 'PLANTA', 'ENVENENADO', NULL, NULL, NULL);
INSERT INTO MOVIMIENTOS VALUES (49, 'Megaagotar', 35, 10, 'ATAQUE', 40, 'PLANTA', NULL, NULL, NULL, NULL);
INSERT INTO MOVIMIENTOS VALUES (50, 'Energibola', 45, 10, 'ATAQUE', 90, 'PLANTA', NULL, NULL, NULL, NULL);

-- Movimientos de tipo Dragón (para Dratini, Dragonair, Dragonite)
INSERT INTO MOVIMIENTOS VALUES (51, 'Garra Dragón', 35, 15, 'ATAQUE', 80, 'DRAGÓN', NULL, NULL, NULL, NULL);
INSERT INTO MOVIMIENTOS VALUES (52, 'Pulso Dragón', 45, 10, 'ATAQUE', 85, 'DRAGÓN', NULL, NULL, NULL, NULL);
INSERT INTO MOVIMIENTOS VALUES (53, 'Cola Dragón', 50, 10, 'ATAQUE', 60, 'DRAGÓN', NULL, NULL, NULL, NULL);
INSERT INTO MOVIMIENTOS VALUES (54, 'Cometa Draco', 48, 5, 'ATAQUE', 130, 'DRAGÓN', NULL, NULL, NULL, NULL);
INSERT INTO MOVIMIENTOS VALUES (55, 'Vozarrón', 30, 10, 'ATAQUE', 60, 'DRAGÓN', NULL, NULL, NULL, NULL);
INSERT INTO MOVIMIENTOS VALUES (56, 'Dragoaliento', 25, 20, 'ATAQUE', 60, 'DRAGÓN', NULL, NULL, NULL, NULL);
INSERT INTO MOVIMIENTOS VALUES (57, 'Garra Umbría', 40, 15, 'ATAQUE', 70, 'DRAGÓN', NULL, NULL, NULL, NULL);
INSERT INTO MOVIMIENTOS VALUES (58, 'Danza Dragón', 50, 20, 'MEJORA', NULL, 'DRAGÓN', NULL, NULL, 'ATAQUE', 1);
INSERT INTO MOVIMIENTOS VALUES (59, 'Furia Dragón', 30, 10, 'ATAQUE', 45, 'DRAGÓN', NULL, NULL, NULL, NULL);
INSERT INTO MOVIMIENTOS VALUES (60, 'Meteo', 55, 5, 'ATAQUE', 120, 'DRAGÓN', NULL, NULL, NULL, NULL);

-- Movimientos adicionales para completar los 110, manteniendo los tipos especificados
INSERT INTO MOVIMIENTOS VALUES (61, 'Fuego Fatuo', 40, 15, 'ESTADO', NULL, 'FUEGO', 'QUEMADO', NULL, NULL, NULL);
INSERT INTO MOVIMIENTOS VALUES (62, 'Llamarada', 45, 5, 'ATAQUE', 110, 'FUEGO', 'QUEMADO', NULL, NULL, NULL);
INSERT INTO MOVIMIENTOS VALUES (63, 'Beso Amoroso', 25, 10, 'ESTADO', NULL, 'HADA', 'ENAMORADO', NULL, NULL, NULL);
INSERT INTO MOVIMIENTOS VALUES (64, 'Deseo', 40, 10, 'ESTADO', NULL, 'HADA', NULL, NULL, NULL, NULL);
INSERT INTO MOVIMIENTOS VALUES (65, 'Malicioso', 30, 15, 'ESTADO', NULL, 'VENENO', NULL, NULL, 'DEFENSA', -1);
INSERT INTO MOVIMIENTOS VALUES (66, 'Puya Nociva', 22, 15, 'ATAQUE', 80, 'VENENO', NULL, NULL, NULL, NULL);
INSERT INTO MOVIMIENTOS VALUES (67, 'Ataque Rápido', 10, 30, 'ATAQUE', 40, 'NORMAL', NULL, NULL, NULL, NULL);
INSERT INTO MOVIMIENTOS VALUES (68, 'Restaurar', 35, 10, 'ESTADO', NULL, 'NORMAL', NULL, NULL, NULL, NULL);
INSERT INTO MOVIMIENTOS VALUES (69, 'Hoja Mágica', 30, 20, 'ATAQUE', 60, 'PLANTA', NULL, NULL, NULL, NULL);
INSERT INTO MOVIMIENTOS VALUES (70, 'Gigadrenado', 50, 5, 'ATAQUE', 75, 'PLANTA', NULL, NULL, NULL, NULL);
INSERT INTO MOVIMIENTOS VALUES (71, 'Torbellino', 40, 20, 'ATAQUE', 40, 'DRAGÓN', NULL, NULL, NULL, NULL);
INSERT INTO MOVIMIENTOS VALUES (72, 'Dracoflecha', 55, 5, 'ATAQUE', 130, 'DRAGÓN', NULL, NULL, NULL, NULL);
INSERT INTO MOVIMIENTOS VALUES (73, 'Furia', 20, 20, 'ATAQUE', 20, 'NORMAL', NULL, NULL, NULL, NULL);
INSERT INTO MOVIMIENTOS VALUES (74, 'Corte', 15, 30, 'ATAQUE', 50, 'NORMAL', NULL, NULL, NULL, NULL);
INSERT INTO MOVIMIENTOS VALUES (75, 'Golpe Rápido', 20, 30, 'ATAQUE', 40, 'NORMAL', NULL, NULL, NULL, NULL);
INSERT INTO MOVIMIENTOS VALUES (76, 'Amortiguador', 30, 20, 'ATAQUE', 70, 'NORMAL', NULL, NULL, NULL, NULL);
INSERT INTO MOVIMIENTOS VALUES (77, 'Grito', 20, 40, 'ESTADO', NULL, 'NORMAL', NULL, NULL, 'ATAQUE', -1);
INSERT INTO MOVIMIENTOS VALUES (78, 'Danza Espada', 30, 20, 'MEJORA', NULL, 'NORMAL', NULL, NULL, 'ATAQUE', 2);
INSERT INTO MOVIMIENTOS VALUES (79, 'Protección', 10, 10, 'ESTADO', NULL, 'NORMAL', NULL, NULL, NULL, NULL);
INSERT INTO MOVIMIENTOS VALUES (80, 'Reflejo', 20, 20, 'MEJORA', NULL, 'NORMAL', NULL, NULL, 'DEFENSA', 2);
INSERT INTO MOVIMIENTOS VALUES (81, 'Pantalla Luz', 30, 30, 'MEJORA', NULL, 'PSÍQUICO', NULL, NULL, 'DEFENSA ESPECIAL', 1);
INSERT INTO MOVIMIENTOS VALUES (82, 'Doble Equipo', 15, 15, 'MEJORA', NULL, 'NORMAL', NULL, NULL, 'EVASION', 1);
INSERT INTO MOVIMIENTOS VALUES (83, 'Recuperación', 40, 10, 'ESTADO', NULL, 'NORMAL', NULL, NULL, NULL, NULL);
INSERT INTO MOVIMIENTOS VALUES (84, 'Fuerza Lunar', 45, 5, 'ATAQUE', 95, 'HADA', NULL, NULL, NULL, NULL);
INSERT INTO MOVIMIENTOS VALUES (85, 'Terapia', 30, 10, 'ESTADO', NULL, 'NORMAL', NULL, NULL, NULL, NULL);
INSERT INTO MOVIMIENTOS VALUES (86, 'Beso Dulce', 25, 10, 'ESTADO', NULL, 'HADA', 'CONFUSO', NULL, NULL, NULL);
INSERT INTO MOVIMIENTOS VALUES (87, 'Ataque Arena', 20, 15, 'ESTADO', NULL, 'TIERRA', NULL, NULL, 'PRECISION', -1);
INSERT INTO MOVIMIENTOS VALUES (88, 'Bomba Lodo', 35, 10, 'ATAQUE', 90, 'VENENO', NULL, NULL, NULL, NULL);
INSERT INTO MOVIMIENTOS VALUES (89, 'Polvo Espora', 20, 15, 'ESTADO', NULL, 'PLANTA', 'DORMIDO', NULL, NULL, NULL);
INSERT INTO MOVIMIENTOS VALUES (90, 'Rizo Defensa', 40, 40, 'MEJORA', NULL, 'HADA', NULL, NULL, 'DEFENSA', 1);
INSERT INTO MOVIMIENTOS VALUES (91, 'Moflete Estático', 20, 15, 'ATAQUE', 20, 'HADA', NULL, NULL, NULL, NULL);
INSERT INTO MOVIMIENTOS VALUES (92, 'Beso Drenaje', 25, 10, 'ATAQUE', 50, 'HADA', NULL, NULL, NULL, NULL);
INSERT INTO MOVIMIENTOS VALUES (93, 'Fuerza Equina', 45, 10, 'ATAQUE', 95, 'HADA', NULL, NULL, NULL, NULL);
INSERT INTO MOVIMIENTOS VALUES (94, 'Deseo Oculto', 30, 15, 'ATAQUE', 70, 'HADA', NULL, NULL, NULL, NULL);
INSERT INTO MOVIMIENTOS VALUES (95, 'Aromaterapia', 30, 5, 'ESTADO', NULL, 'PLANTA', NULL, NULL, NULL, NULL);
INSERT INTO MOVIMIENTOS VALUES (96, 'Beso Amoroso', 25, 10, 'ESTADO', NULL, 'HADA', 'ENAMORADO', NULL, NULL, NULL);
INSERT INTO MOVIMIENTOS VALUES (97, 'Manto Espejo', 40, 15, 'MEJORA', NULL, 'HADA', NULL, NULL, 'DEFENSA ESPECIAL', 2);
INSERT INTO MOVIMIENTOS VALUES (98, 'Meteo', 55, 5, 'ATAQUE', 120, 'DRAGÓN', NULL, NULL, NULL, NULL);
INSERT INTO MOVIMIENTOS VALUES (99, 'Garra Umbría', 40, 15, 'ATAQUE', 70, 'DRAGÓN', NULL, NULL, NULL, NULL);
INSERT INTO MOVIMIENTOS VALUES (100, 'Danza Dragón', 50, 20, 'MEJORA', NULL, 'DRAGÓN', NULL, NULL, 'ATAQUE', 1);
INSERT INTO MOVIMIENTOS VALUES (101, 'Furia Dragón', 30, 10, 'ATAQUE', 45, 'DRAGÓN', NULL, NULL, NULL, NULL);
INSERT INTO MOVIMIENTOS VALUES (102, 'Dragoaliento', 25, 20, 'ATAQUE', 60, 'DRAGÓN', NULL, NULL, NULL, NULL);
INSERT INTO MOVIMIENTOS VALUES (103, 'Garra Dragón', 35, 15, 'ATAQUE', 80, 'DRAGÓN', NULL, NULL, NULL, NULL);
INSERT INTO MOVIMIENTOS VALUES (104, 'Pulso Dragón', 45, 10, 'ATAQUE', 85, 'DRAGÓN', NULL, NULL, NULL, NULL);
INSERT INTO MOVIMIENTOS VALUES (105, 'Cola Dragón', 50, 10, 'ATAQUE', 60, 'DRAGÓN', NULL, NULL, NULL, NULL);
INSERT INTO MOVIMIENTOS VALUES (106, 'Cometa Draco', 48, 5, 'ATAQUE', 130, 'DRAGÓN', NULL, NULL, NULL, NULL);
INSERT INTO MOVIMIENTOS VALUES (107, 'Vozarrón', 30, 10, 'ATAQUE', 60, 'DRAGÓN', NULL, NULL, NULL, NULL);
INSERT INTO MOVIMIENTOS VALUES (108, 'Torbellino', 40, 20, 'ATAQUE', 40, 'DRAGÓN', NULL, NULL, NULL, NULL);
INSERT INTO MOVIMIENTOS VALUES (109, 'Dracoflecha', 55, 5, 'ATAQUE', 130, 'DRAGÓN', NULL, NULL, NULL, NULL);
INSERT INTO MOVIMIENTOS VALUES (110, 'Meteo', 55, 5, 'ATAQUE', 120, 'DRAGÓN', NULL, NULL, NULL, NULL);



CREATE TABLE Movimiento_Pokemon (
    ID_POKEMON INT,
    ID_MOVIMIENTO INT,
    PP_ACTUALES INT,
   CONSTRAINT MOV_POK_PK PRIMARY KEY (ID_MOVIMIENTO, ID_POKEMON)
);

INSERT INTO Movimiento_Pokemon (ID_POKEMON, ID_MOVIMIENTO, PP_ACTUALES) VALUES (25, 1, 15);
INSERT INTO Movimiento_Pokemon (ID_POKEMON, ID_MOVIMIENTO, PP_ACTUALES) VALUES (25, 2, 20); 

CREATE TABLE Objeto (
    ID_OBJETO INT PRIMARY KEY,
    NOM_OBJETO VARCHAR(50) NOT NULL,
    ATAQUE INT,
    AT_ESPECIAL INT,
    DEFENSA INT,
    DEF_ESPECIAL INT,
    VELOCIDAD INT,
    PRECIO INT
);

INSERT INTO OBJETO (ID_OBJETO, NOM_OBJETO, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD, PRECIO)  
VALUES 
(1, 'Pesa', 20, NULL, 20, NULL, -20, NULL),  
(2, 'Pluma', NULL, NULL, -20, -20, 30, NULL),  
(3, 'Chaleco', -15, NULL, 20, 20, -15, NULL),  
(4, 'Bastón', NULL, NULL, NULL, NULL, -15, NULL),  
(5, 'Pilas', NULL, NULL, NULL, -30, NULL, NULL),  
(6, 'Éter', NULL, NULL, NULL, NULL, NULL, NULL),  
(7, 'Anillo único', 0, NULL, NULL, NULL, NULL, NULL),  
(8, 'Pokéball', NULL, NULL, NULL, NULL, NULL, 50);  

CREATE TABLE Mochila(
	ID_ENTRENADOR INT,
	ID_OBJETO INT,
	NUMERO_OBJETOS INT NOT NULL,
CONSTRAINT MOCHI_PK PRIMARY KEY(ID_ENTRENADOR,ID_OBJETO)
);

INSERT INTO Mochila (ID_ENTRENADOR, ID_OBJETO, NUMERO_OBJETOS)
VALUES (1, 101, 5);

/* Añadir mas insert y hacer update */
ALTER TABLE entrenador MODIFY COLUMN ID_ENTRENADOR INT AUTO_INCREMENT;

-- Charmander macho
INSERT INTO POKEMON (
    FKID_ENTRENADOR, FK_NUM_POKEDEX, NOMBRE, VITALIDAD, ATAQUE, DEFENSA, AT_ESPECIAL, DEF_ESPECIAL, VELOCIDAD,
    NIVEL, FERTILIDAD, SEXO, ESTADO, EQUIPO
) VALUES (
    25, 4, 'Charmander', 39, 52, 43, 60, 50, 65,
    10, 5, 'M', 'Sano', 1
);

-- Vulpix hembra
INSERT INTO POKEMON (
    FKID_ENTRENADOR, FK_NUM_POKEDEX, NOMBRE, VITALIDAD, ATAQUE, DEFENSA, AT_ESPECIAL, DEF_ESPECIAL, VELOCIDAD,
    NIVEL, FERTILIDAD, SEXO, ESTADO, EQUIPO
) VALUES (
    25, 37, 'Vulpix', 38, 41, 40, 50, 65, 65,
    10, 5, 'F', 'Sano', 1
);
